#==============================================================================
#title           :F5-Search.yml
#description     :This playbook will call F5-Search.py script to search string
#                 in all F5 configuration backups.
#author          :June Wang
#date            :2019-03-12
#usage           :Called by Ansible AWX job template
#==============================================================================

---
- name: Search a string from all bigip.conf files
  hosts: all
  connection: local
#  ignore_errors: yes
#  vars_files:
#    - '../.FA-AUTOMATION'
#    - '../.vars.yml'
#    - 'vars/vars-Search-pool-VS'

  tasks:
  - name: Search for all F5's bigip.conf files and print out F5 name and IP 
    command: python F5-Search.py {{ String }}
    register: output
  - debug: var=output.stdout_lines
